// <auto-generated />
using GovBr.Currency.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GovBr.Currency.Repository.Migrations
{
    [DbContext(typeof(CurrencyContext))]
    partial class CurrencyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GovBr.Currency.Service.Models.Exchange", b =>
                {
                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Country");

                    b.ToTable("Exchanges");

                    b.HasData(
                        new
                        {
                            Country = "ÍNDIA",
                            Code = "INR",
                            Currency = "Rupia indiana",
                            Number = 356
                        },
                        new
                        {
                            Country = "ÁUSTRIA",
                            Code = "EUR",
                            Currency = "Euro",
                            Number = 978
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
